# Generated by Django 4.1.7 on 2023-04-12 03:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invitation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="subgroup",
        ),
    ]
