# Generated by Django 4.1.7 on 2023-04-12 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invitation", "0002_remove_invitation_subgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="inviter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_invitation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_invitation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
