# Generated by Django 4.1.7 on 2023-04-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invitation", "0003_alter_invitation_inviter_alter_invitation_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="code",
            field=models.CharField(
                default="eebc6bb0fccad803a994095d0717ef", max_length=30
            ),
        ),
    ]
