# Generated by Django 4.1.7 on 2023-04-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invitation", "0004_alter_invitation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="code",
            field=models.CharField(
                default="c62023a1228d25c276e26cb10a9481", max_length=30
            ),
        ),
    ]
