# Generated by Django 4.1.7 on 2023-04-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invitation", "0005_alter_invitation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="code",
            field=models.CharField(
                default="b0864fa1bfdfac0282876ede16e3ea", max_length=30
            ),
        ),
    ]
