# Generated by Django 4.1.7 on 2023-04-14 09:53

from django.db import migrations, models
import tools.hasher


class Migration(migrations.Migration):
    dependencies = [
        ("invitation", "0006_alter_invitation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="code",
            field=models.CharField(default=tools.hasher.Hasher.hash, max_length=30),
        ),
    ]
