version: "3.9"

services:
  be:
    build: ./copy_chat_be
    ports:
      - 8000:8000
    restart: unless-stopped
    extra_hosts:
    - "host.docker.internal:172.17.0.1"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - ./copy_chat_be/deploy/redis/data:/data
      - ./copy_chat_be/deploy/redis/conf/redis.conf:/usr/local/conf/redis.conf
    command: redis-server /usr/local/conf/redis.conf
  fe:
    build: ./copy_chat_fe
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./copy_chat_fe/certbot/www/:/var/www/certbot/:ro
      - ./copy_chat_fe/certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./copy_chat_fe/certbot/www/:/var/www/certbot/:rw
      - ./copy_chat_fe/certbot/conf/:/etc/letsencrypt/:rw
