version: "3.9"

services:
  django:
    restart: unless-stopped
    build: ./copychat-be
    ports:
      - 8000:8000
  nginx:
    build: ./copychat-fe
    restart: unless-stopped
    ports:
      - 443:443
    depends_on:
      - django
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
