# Generated by Django 4.1.7 on 2023-03-17 09:05

import account.profile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        upload_to=account.profile.models.user_directory_path
                    ),
                ),
                (
                    "short_comment",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "long_comment",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "accout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
