# Generated by Django 4.1.7 on 2023-04-02 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0002_group_invitationneeded_group_searchable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subgroup",
            name="members",
        ),
        migrations.RemoveField(
            model_name="subgroup",
            name="parent",
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subgroups",
                to="group.group",
            ),
        ),
    ]
