version: "3.8"

services:
  django:
    build: .
    ports:
      - 8000:8000
    restart: unless-stopped
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - ./deploy/redis/data:/data
      - ./deploy/redis/conf/redis.conf:/usr/local/conf/redis.conf
    command: redis-server /usr/local/conf/redis.conf
