# Generated by Django 4.1.7 on 2023-04-14 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0006_alter_channel_unique_together_alter_channel_group_and_more"),
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="subgroup",
        ),
        migrations.AddField(
            model_name="message",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="group.channel",
            ),
        ),
    ]
