# Generated by Django 4.1.7 on 2023-03-17 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("state", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="state",
            name="description",
        ),
        migrations.RemoveField(
            model_name="state",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="state",
            name="until",
        ),
        migrations.AddField(
            model_name="state",
            name="type",
            field=models.CharField(
                choices=[
                    ("ONL", "online"),
                    ("STO", "step out"),
                    ("CAL", "call in progress"),
                    ("OFF", "offline"),
                ],
                default="OFF",
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="CustomState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=100)),
                ("until", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
