# Generated by Django 4.1.7 on 2023-04-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0002_group_invitationneeded_group_searchable"),
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupmembership",
            unique_together={("group", "name")},
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="groupmembership",
            unique_together={("group", "is_default"), ("group", "name")},
        ),
    ]
