# Generated by Django 4.1.7 on 2023-04-07 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0006_alter_channel_unique_together_alter_channel_group_and_more"),
        ("membership", "0002_alter_groupmembership_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmembership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="group.group",
            ),
        ),
    ]
