# Generated by Django 4.1.7 on 2023-03-17 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("group", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubGroupRoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("invite_member", models.BooleanField(default=True)),
                ("kick_member", models.BooleanField(default=True)),
                ("create_subgroup", models.BooleanField(default=True)),
                ("manage_permission", models.BooleanField(default=True)),
                ("members", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                (
                    "subgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="group.subgroup"
                    ),
                ),
            ],
            options={
                "unique_together": {("subgroup", "name")},
            },
        ),
        migrations.CreateModel(
            name="GroupRoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("invite_member", models.BooleanField(default=True)),
                ("kick_member", models.BooleanField(default=True)),
                ("create_subgroup", models.BooleanField(default=True)),
                ("manage_permission", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="group.group"
                    ),
                ),
                ("members", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("group", "name")},
            },
        ),
    ]
